[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
